// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindEventsHandlerFunc turns a function with the right signature into a find events handler
type FindEventsHandlerFunc func(FindEventsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindEventsHandlerFunc) Handle(params FindEventsParams) middleware.Responder {
	return fn(params)
}

// FindEventsHandler interface for that can handle valid find events params
type FindEventsHandler interface {
	Handle(FindEventsParams) middleware.Responder
}

// NewFindEvents creates a new http.Handler for the find events operation
func NewFindEvents(ctx *middleware.Context, handler FindEventsHandler) *FindEvents {
	return &FindEvents{Context: ctx, Handler: handler}
}

/*FindEvents swagger:route GET /events events findEvents

FindEvents find events API

*/
type FindEvents struct {
	Context *middleware.Context
	Handler FindEventsHandler
}

func (o *FindEvents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindEventsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
