// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is CalcuCo's awesome calculator. \u003cbr\u003e \u003cbr\u003eOperation supported: \u003cbr\u003e \u003col\u003e\u003cli\u003eAdd - ` + "`" + `add` + "`" + ` \u003c/li\u003e \u003cli\u003eSubtract - ` + "`" + `sub` + "`" + `\u003c/li\u003e\u003cli\u003eMultiply - ` + "`" + `multi` + "`" + `\u003c/li\u003e\u003cli\u003eDivide - ` + "`" + `div` + "`" + `\u003c/li\u003e\u003cli\u003eSquare root - ` + "`" + `sqrt` + "`" + `\u003c/li\u003e\u003cli\u003eQubic root - ` + "`" + `cbrt` + "`" + `\u003c/li\u003e\u003cli\u003ePower - ` + "`" + `pow` + "`" + `\u003c/li\u003e\u003cli\u003eFactorial - ` + "`" + `fac` + "`" + `\u003c/li\u003e\u003col\u003e",
    "title": "CalcuCo's calculator",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/calc/{operation}/{args}": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Operation would either be: \u003col\u003e\u003cli\u003eAdd - ` + "`" + `add` + "`" + ` \u003c/li\u003e \u003cli\u003eSubtract - ` + "`" + `sub` + "`" + `\u003c/li\u003e\u003cli\u003eMultiply - ` + "`" + `multi` + "`" + `\u003c/li\u003e\u003cli\u003eDivide - ` + "`" + `div` + "`" + `\u003c/li\u003e\u003cli\u003eSquare root - ` + "`" + `sqrt` + "`" + `\u003c/li\u003e\u003cli\u003eQubic root - ` + "`" + `cbrt` + "`" + `\u003c/li\u003e\u003cli\u003ePower - ` + "`" + `pow` + "`" + `\u003c/li\u003e\u003cli\u003eFactorial - ` + "`" + `fac` + "`" + `\u003c/li\u003e\u003col\u003e",
        "tags": [
          "calc"
        ],
        "summary": "Performs mathematical computations",
        "operationId": "calcOperation",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "number",
              "format": "float"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "pattern": "^(add|sub|multi|div|sqrt|cbrt|pow|fac)$",
          "type": "string",
          "name": "operation",
          "in": "path",
          "required": true
        },
        {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          },
          "name": "args",
          "in": "path",
          "required": true
        }
      ]
    },
    "/report": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "report"
        ],
        "operationId": "findReports",
        "parameters": [
          {
            "type": "string",
            "format": "date-time",
            "name": "start",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "name": "end",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list all events",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/report"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "report": {
      "type": "object",
      "properties": {
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "user": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Event's API information",
      "name": "report"
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is CalcuCo's awesome calculator. \u003cbr\u003e \u003cbr\u003eOperation supported: \u003cbr\u003e \u003col\u003e\u003cli\u003eAdd - ` + "`" + `add` + "`" + ` \u003c/li\u003e \u003cli\u003eSubtract - ` + "`" + `sub` + "`" + `\u003c/li\u003e\u003cli\u003eMultiply - ` + "`" + `multi` + "`" + `\u003c/li\u003e\u003cli\u003eDivide - ` + "`" + `div` + "`" + `\u003c/li\u003e\u003cli\u003eSquare root - ` + "`" + `sqrt` + "`" + `\u003c/li\u003e\u003cli\u003eQubic root - ` + "`" + `cbrt` + "`" + `\u003c/li\u003e\u003cli\u003ePower - ` + "`" + `pow` + "`" + `\u003c/li\u003e\u003cli\u003eFactorial - ` + "`" + `fac` + "`" + `\u003c/li\u003e\u003col\u003e",
    "title": "CalcuCo's calculator",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/calc/{operation}/{args}": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Operation would either be: \u003col\u003e\u003cli\u003eAdd - ` + "`" + `add` + "`" + ` \u003c/li\u003e \u003cli\u003eSubtract - ` + "`" + `sub` + "`" + `\u003c/li\u003e\u003cli\u003eMultiply - ` + "`" + `multi` + "`" + `\u003c/li\u003e\u003cli\u003eDivide - ` + "`" + `div` + "`" + `\u003c/li\u003e\u003cli\u003eSquare root - ` + "`" + `sqrt` + "`" + `\u003c/li\u003e\u003cli\u003eQubic root - ` + "`" + `cbrt` + "`" + `\u003c/li\u003e\u003cli\u003ePower - ` + "`" + `pow` + "`" + `\u003c/li\u003e\u003cli\u003eFactorial - ` + "`" + `fac` + "`" + `\u003c/li\u003e\u003col\u003e",
        "tags": [
          "calc"
        ],
        "summary": "Performs mathematical computations",
        "operationId": "calcOperation",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "number",
              "format": "float"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "pattern": "^(add|sub|multi|div|sqrt|cbrt|pow|fac)$",
          "type": "string",
          "name": "operation",
          "in": "path",
          "required": true
        },
        {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          },
          "name": "args",
          "in": "path",
          "required": true
        }
      ]
    },
    "/report": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "report"
        ],
        "operationId": "findReports",
        "parameters": [
          {
            "type": "string",
            "format": "date-time",
            "name": "start",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "name": "end",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list all events",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/report"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "report": {
      "type": "object",
      "properties": {
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "user": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Event's API information",
      "name": "report"
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}`))
}
