// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindReportsHandlerFunc turns a function with the right signature into a find reports handler
type FindReportsHandlerFunc func(FindReportsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FindReportsHandlerFunc) Handle(params FindReportsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FindReportsHandler interface for that can handle valid find reports params
type FindReportsHandler interface {
	Handle(FindReportsParams, interface{}) middleware.Responder
}

// NewFindReports creates a new http.Handler for the find reports operation
func NewFindReports(ctx *middleware.Context, handler FindReportsHandler) *FindReports {
	return &FindReports{Context: ctx, Handler: handler}
}

/*FindReports swagger:route GET /report report findReports

FindReports find reports API

*/
type FindReports struct {
	Context *middleware.Context
	Handler FindReportsHandler
}

func (o *FindReports) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindReportsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
