// Code generated by go-swagger; DO NOT EDIT.

package calc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// CalcOperationURL generates an URL for the calc operation operation
type CalcOperationURL struct {
	Args      []int64
	Operation string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CalcOperationURL) WithBasePath(bp string) *CalcOperationURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CalcOperationURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *CalcOperationURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/calc/{operation}/{args}"

	var argsIR []string
	for _, argsI := range o.Args {
		argsIS := swag.FormatInt64(argsI)
		if argsIS != "" {
			argsIR = append(argsIR, argsIS)
		}
	}

	args := swag.JoinByFormat(argsIR, "")
	if len(args) > 0 {
		psv := args[0]
		if psv != "" {
			_path = strings.Replace(_path, "{args}", psv, -1)
		} else {
			return nil, errors.New("args is required on ArgsURL")
		}
	}

	operation := o.Operation
	if operation != "" {
		_path = strings.Replace(_path, "{operation}", operation, -1)
	} else {
		return nil, errors.New("operation is required on CalcOperationURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CalcOperationURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CalcOperationURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CalcOperationURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CalcOperationURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CalcOperationURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CalcOperationURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
